routes/web.php
<?php

use App\Http\Controllers\Auth\AuthenticationController;
use App\Http\Controllers\Auth\HomeController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthenticationController::class, 'login'])->name('login');



Route::group(['middleware' => 'guest'], function () {
        Route::get('login/google', [AuthenticationController::class, 'redirectToGoogle'])->name('login.google');
        Route::get('login/google/callback', [AuthenticationController::class, 'handleGoogleCallback'])->name('login.google.callback');
});

Route::group(['middleware' => 'users'], function () {

        Route::get('dashboard', [HomeController::class, 'index'])->name('home');

        /**
         * User Resources with CRUD operation
         */
        // Route::resource('users', UserController::class);

        Route::get('users', [UserController::class, 'index'])->name('users.list');

        Route::get('users/create', [UserController::class, 'create'])->name('users.create');

        Route::post('users/store', [UserController::class, 'store'])->name('users.store');
        
        Route::get('users/cities/{countryId}', [UserController::class, 'getCountryBasedCities'])->name('users.cities');

        Route::get('users/{id}/edit', [UserController::class, 'edit'])->name('users.details.edit');

        Route::post('users/update', [UserController::class, 'update'])->name('users.details.update');

        Route::get('users/delete/{id?}', [UserController::class, 'delete'])->name('users.details.delete');

        Route::get('users/{id}/view', [UserController::class, 'show'])->name('users.details.show');

        Route::any('/logout', [AuthenticationController::class, 'logout'])->name('logout');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function userDetails()
    {
        return $this->hasOne(UserDetail::class, 'user_id', 'id');
    }

    
}

app/Models/UserDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class UserDetail extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'dob',
        'address',
        'education_id',
        'profilepic',
        'country_id',
        'pincode',
        'city_id'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'dob' => 'datetime',
    ];

    /**
     * Get the user that related to the table.
     */
    public function userDetails()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function getDateOfBirthAttribute()
    {
        return $this->dob ? date('d M, Y', strtotime($this->dob)) : '' ;
    }

    public function userEducation()
    {
        return $this->hasOne(EducationCategory::class, 'id', 'education_id');
    }

    public function userCountry()
    {
        return $this->hasOne(Country::class, 'id', 'country_id');
    }

    public function userCity()
    {
        return $this->hasOne(City::class, 'id', 'city_id');
    }

    public function getUserProfileImageAttribute()
    {
        return ($this->profilepic && Storage::exists('public/profile_pic/thumbnails/' . $this->profilepic)) ? Storage::url('public/profile_pic/thumbnails/' . $this->profilepic) : asset('images/avatar.jpg');
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\DataTables\UsersListDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserDetailsRequest;
use App\Models\City;
use App\Models\Country;
use App\Models\EducationCategory;
use App\Models\User;
use App\Repositories\UserRepository;
use Exception;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{

    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function index(UsersListDataTable $dataTable)
    {
        $users = User::all()->except(Auth::user());
        return $dataTable->render('user.user-list', ['users' => $users]);
    }

    public function create()
    {
        $education = EducationCategory::all();
        $country = Country::all();
        return View('user.create-user', compact('education', 'country'));
    }

    public function getCountryBasedCities($countryId)
    {   
        try {

            $cities = City::where('country_id', $countryId)->pluck('name', 'id');
            
            if($cities->count()) {
                return response()->json([
                    'success' => true,
                    'message' => 'Cities listed successfully!',
                    'data' => $cities,
                    'code' => 200
                ], 200);
            }

            return response()->json([
                'success' => false,
                'message' => 'No details found with this country!',
                'errors' => [],
                'code' => 200
            ], 200);

            /** API through fetching city  names */
                // $countries = Country::find($countryId);
    
                // $client = new Client();
                // $response = $client->request('POST', 'https://countriesnow.space/api/v0.1/countries/cities', [
                //     'form_params' => [
                //         "country" => $countries->name//strtolower($value->name)
                //     ]
                // ]);
    
                // $response = $response->getBody()->getContents();
                // $data = json_decode($response);
                // foreach($data->data as $k => $value){
                //     $cityName[] = $value;
                // }

                // if(!$data->error) {

                //     return response()->json([
                //             'success' => true,
                //             'message' => $data->msg,
                //             'data' => $cityName,
                //             'code' => 200
                //         ], 200);
                // } 

                /** end */
            
        // } catch(ConnectException $e){
        //     return response()->json([
        //         'success' => false,
        //         'message' => $e->getMessage(),
        //         'errors' => [],
        //         'code' => $e->getCode()
        //     ], $e->getCode());
        // } catch(GuzzleException $guzzleException){
        //     $expection = $guzzleException;
        //     if ($expection instanceof RequestException) {
        //         $exceptionResponse = $expection->getResponse();
        //         if($exceptionResponse) {                    
        //             $this->statusCode = $exceptionResponse->getStatusCode();
        //             $this->message = $exceptionResponse->getReasonPhrase();
        //         }
        //     }
        //     return response()->json([
        //         'success' => false,
        //         'message' => $this->message,
        //         'errors' => [],
        //         'code' => $this->statusCode
        //     ], $this->statusCode);
        }
        catch(Exception $e){
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());

        }
    }

    public function store (StoreUserDetailsRequest $request)
    {
        try {

            $user = $this->userRepository->createNew($request->all());

            return response()->json([
                'success' => true,
                'message' => 'User Created Successfully!',
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }

    public function show($id) {

        $user = User::find($id);
        if($user) {
            $userDetails = $user->userDetails; 
            
            return View('user.view-user', compact('user', 'userDetails'));
        }
        
        return back()->with('commonError', 'User data not found!');
    }

    public function edit($id)
    {
        $user = User::find($id);
        if($user) {
            $userDetails = $user->userDetails; 
            
            $country = Country::all();
            $city = '';
            $education = EducationCategory::all();

            if($userDetails && $userDetails->country_id) {
                $city = City::where('country_id', $userDetails->country_id)->pluck('name', 'id');
            }

            return View('user.edit-user', compact('user', 'userDetails', 'country', 'city', 'education'));
        }
        
        return back()->with('commonError', 'User data not found!');

        
    }

    public function update (StoreUserDetailsRequest $request)
    {
        try {

            $user = $this->userRepository->updateUserInfo($request->user_id, $request->all());

            return response()->json([
                'success' => true,
                'message' => 'User Details Updated Successfully!',
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }

    public function delete($id)
    {
        try {

            $user = User::find($id)->delete();

            return response()->json([
                'success' => true,
                'message' => 'User deleted successfully!',
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }
}

resources/views/user/create-user.blade.php
@extends('layouts.app')
@section('pageTitle','New User')

@push('css')
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />

<style>
input.radio {
    margin-left: 3% !important;
}

select.is-invalid + .select2 .select2-selection {
    /* background-color: red !important; */
    border-color: red !important;
}
.is-invalid {
    border-color: red !important;
}

select.no-data + .select2 .select2-selection{
    pointer-events: none !important;
}
</style>
@endpush
@section('content')


    <div class="row col-6 center">
 
        <!-- <div class="relative items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0"> -->
            
            <div class="card" style="margin-left: 50%;">
                <div class="card-body">
                    <form role="form text-left" id="user-details" data-url="{{ route('users.store') }}">
                        <label class="form-label">Name</label>
                        <div class="input-group input-group-outline my-3">
                            <input type="text" class="form-control" name="name" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123)">
                        </div>

                        <label class="form-label">Email</label>
                        <div class="input-group input-group-outline my-3">
                            <input type="email" class="form-control" name="email">
                        </div>

                        <label class="form-label">Address</label>
                        <div class="input-group input-group-outline my-3">
                            <textarea name="address" class="form-control"></textarea>
                        </div>

                        <label class="form-label">Date of Birth</label>
                        <div class="input-group input-group-outline my-3">
                            <input type="text" id="dob" name="dob" class="form-control" placeholder="dd-mm-yyyy">
                        </div>

                        <label class="form-label">Status</label>
                        <div class="input-group input-group-outline my-3">
                            <input type="radio" class="radio" id="active" name="status" value="1" checked> Active
                            <input type="radio" class="radio" id="inactive" name="status" value="0">Inactive

                        </div>

                        <label class="form-label">Education</label>
                        <div class="input-group input-group-outline my-3">
                            <select id="education" name="education" class="form-control">
                                <option value="" disabled selected> Choose education</option>
                                @foreach($education as $key => $edu)
                                    <option value="{{$edu->id}}">{{$edu->education}}</option>
                                @endforeach
                            </select>
                        </div>

                        <label class="form-label">Country</label>
                        <div class="input-group input-group-outline my-3">
                            <select id="country" name="country" class="form-control">
                                <option value=""> Choose country </option>
                                @foreach($country as $key => $countryDetails)
                                    <option value="{{$countryDetails->id}}">{{$countryDetails->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <label class="form-label">City</label>
                        <div class="input-group input-group-outline my-3">
                            <select id="city" name="city" class="form-control no-data">
                                <option value=""> Choose city </option>
                                
                            </select>
                        </div>

                        <label class="form-label">Pin Code</label>
                        <div class="input-group input-group-outline my-3">
                            <input type="text" name="pincode" class="form-control">
                        </div>

                        <label class="form-label">Profile Pic</label>
                        <div class="input-group input-group-outline my-3">
                            <img id="output" src="" width="100" height="100" style="display:none;">

                            <input name="profilepic" type="file"   id="profilepic">

                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Save</button>
                        </div>
                            
                    </form>
                </div>
            </div>
            
        <!-- </div> -->
    </div>

@endsection


@push('js')
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
<script src="{{ asset('js/jquery.validate.min.js')}}"></script>
<script src="{{ asset('js/user/create-user.js')}}"></script>
@endpush

resources/views/user/view-user.blade.php
@extends('layouts.app')
@section('pageTitle','User Details')

@section('content')
    <div class="row col-6">
        <div  style="margin-left: 9%;">
            <div class="card mb-4 " style="margin-left: 50%;">
                <div class="d-flex">
                    <div class="icon icon-shape icon-lg shadow text-center border-radius-xl mt-n3 ms-4">
                    <img src="{{($userDetails) ? $userDetails->user_profile_image : asset('images/avatar.jpg')}}" style="width: 64px;height: 64px;" class="material-icons opacity-10">
                    </div>
                    <!-- <h6 class="mt-3 mb-2 ms-3 ">Sales by Country</h6> -->
                </div>
                <div class="card-body p-3">
                    <div class="row">
                        <div class="">
                            <div class="table-responsive">
                                <table class="table align-items-center ">
                                    <tbody>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Name: </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ $user->name }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Email : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ $user->email?:'-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30" style="white-space: inherit;">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Address : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ ($userDetails && $userDetails->address) ? $userDetails->address : '-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">DOB : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ ($userDetails && $userDetails->date_of_birth) ? $userDetails->date_of_birth : '-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Status : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 ">
                                                            @if($user->status == 1)
                                                                <span class="badge badge-sm bg-gradient-success">Active</span>
                                                            @else
                                                                <span class="badge badge-sm bg-gradient-secondary">Inactive</span>
                                                            @endif
                                                        </h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Education : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ ($userDetails && $userDetails->userEducation) ? $userDetails->userEducation->education : '-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>                                            
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Country : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ ($userDetails && $userDetails->userCountry) ? $userDetails->userCountry->name : '-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">City : </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{ ($userDetails && $userDetails->userCity) ? $userDetails->userCity->name : '-' }}</h6>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="w-30">
                                                <div class="d-flex px-2 py-1 align-items-center">
                                                    <div class="col-4">
                                                    <p class="text-xs font-weight-bold mb-0 ">Pin Code: </p>
                                                    </div>
                                                    <div class="ms-4">
                                                        
                                                        <h6 class="text-sm font-weight-normal mb-0 "> {{($userDetails && $userDetails->pincode) ? $userDetails->pincode : '-' }} </h6>
                                                    </div>
                                                </div>
                                            </td>
                                            
                                        </tr>
                                    </tbody>
                                </table>
                                <a href="{{ route('users.list') }}" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


@endsection